THICKNESS=1;
DEPTH=100;
WIDTH=65;
HEIGHT=50;

cube([DEPTH,WIDTH,THICKNESS]);
cube([DEPTH,THICKNESS,HEIGHT]);
translate([0,WIDTH-THICKNESS,0]) cube([DEPTH,THICKNESS,HEIGHT]);
cube([THICKNESS,WIDTH,HEIGHT]);
translate([DEPTH-THICKNESS,0,0]) cube([THICKNESS,WIDTH,HEIGHT]);

DIVIDERS=4;
for (i = [1 : DIVIDERS]) {
translate([i * DEPTH/(DIVIDERS+1)-THICKNESS/2,0,0]) cube([THICKNESS,10,40]);
translate([i* DEPTH/(DIVIDERS+1)-THICKNESS/2,55,0]) cube([THICKNESS,10,40]);
}
